name: Auto

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Generate docs
        run: |
          nix develop .#ci-generate-docs --command bash -c "./build.fnl docs"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: generate docs"
