name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-luajit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Run tests (LuaJIT)
        run: |
          nix develop .#ci-test-luajit --command bash -c "./build.fnl test"

  test-lua5_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Run tests (PUC Lua 5.1)
        run: |
          nix develop .#ci-test-lua5_1 --command bash -c "./build.fnl test"

  test-lua5_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Run tests (PUC Lua 5.2)
        run: |
          nix develop .#ci-test-lua5_2 --command bash -c "./build.fnl test"

  test-lua5_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Run tests (PUC Lua 5.3)
        run: |
          nix develop .#ci-test-lua5_3 --command bash -c "./build.fnl test"

  test-lua5_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Run tests (PUC Lua 5.4)
        run: |
          nix develop .#ci-test-lua5_4 --command bash -c "./build.fnl test"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Check formats
        run: |
          nix develop .#ci-lint --command bash -c "./build.fnl fmt-check"
