name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua:
          - luajit
          - lua5_1
          - lua5_2
          - lua5_3
          - lua5_4
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Run tests (${{ matrix.lua }})
        run: |
          nix develop .#ci-test-stable-${{ matrix.lua }} --command bash -c "./build.fnl test"
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Check format
        run: |
          nix develop .#ci-check-format --command bash -c "./build.fnl check-format"
